#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

path = ARGV[0]
lib = "bin:lib/antlr-4.4-complete.jar"
system "java -cp #{lib} Main #{path}"
ret = $?.exitstatus
if ret==100
  puts "#syntax_error#"
  exit(100)
elsif ret==200
  puts "#semantic_error#"
  exit(200)
end